CI: Fix BASH_ENV handling.
In b97fb253ad ("CI: Run bash/zsh in strict mode"), we used BASH_ENV
to force bash running "set -euo pipefail" before executing any script
in a non-interactive shell. But since BASH_ENV is pointed to
~/.bash_profile, it created an unexpected side-effect: environmental
variables within the shell may disappear in a script, since
~/.bash_profile may contain commands to reset PATH. Use a special
~/.bash_env instead to stop this behavior.

Signed-off-by: Yifeng Li <tomli@tomli.me>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -109,7 +109,11 @@ jobs:
           printf "%s\n" "set -euo pipefail" >> ~/.bash_profile
 
           # For non-interactive shells such as "bash script.sh"
-          echo 'export BASH_ENV="$HOME/.bash_profile"' >> ~/.bash_profile
+          # Use a special ~/.bash_env file because ~/.bash_profile
+          # may contain commands that reset environment variables
+          # such as PATH.
+          printf "%s\n" "set -euo pipefail" >> ~/.bash_env
+          echo 'export BASH_ENV="$HOME/.bash_env"' >> ~/.bash_profile
 
           if grep -q "ID=fedora" /etc/os-release; then
             dnf install -y git
@@ -317,9 +321,13 @@ jobs:
           printf "%s\n" "set -euo pipefail" >> ~/.zprofile
 
           # For #!/bin/bash scripts.
-          # To ensure ~/.bash_profile, BASH_ENV must be set for the current
-          # default shell of which bash is launched from.
-          echo 'export BASH_ENV="$HOME/.bash_profile"' >> ~/.zprofile
+          # To ensure ~/.bash_env is executed, BASH_ENV must be set for the
+          # current default shell of which bash is launched from.
+          # Use a special ~/.bash_env file because ~/.bash_profile
+          # may contain commands that reset environment variables
+          # such as PATH.
+          printf "%s\n" "set -euo pipefail" >> ~/.bash_env
+          echo 'export BASH_ENV="$HOME/.bash_env"' >> ~/.zprofile
 
           # GitHub's default ~/.bash_profile contains:
           #
